---
- hosts: all
  name: global configuration
  gather_facts: true
  become: true

  roles:
    - updates

- hosts: cassandra
  name: Install and configure Cassandra
  gather_facts: true
  become: true
  
  roles:
    - java
    - cassandra